source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PopUpMenu_Example', :exclusive => true do
  pod "PopUpMenu", :path => "../"
end

target 'PopUpMenu_Tests', :exclusive => true do
  pod "PopUpMenu", :path => "../"

  
end
